- name: Create container instances
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Build Container Images
      containers.podman.podman_image:
        name: local/{{ item }}:molecule
        state: present
        path: "{{ playbook_dir }}/"
        build:
          format: docker
          file: "{{ playbook_dir }}/Dockerfile.{{ item }}"
      loop:
        - ubuntu

    - name: Create Containers
      containers.podman.podman_container:
        image: "{{ hostvars[item]['container_image'] }}"
        name: "{{ item }}"
        hostname: "{{ item }}"
        command: sleep 1d
        privileged: false
        systemd: true
        log_driver: json-file
        state: started
      register: result
      loop: "{{ groups['molecule'] }}"

    - name: Wait for Container to be Ready
      ansible.builtin.wait_for_connection:
        timeout: 30
      delegate_to: "{{ item }}"
      loop: "{{ groups['molecule'] }}"
