FROM docker.io/ubuntu:latest

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN set -e \
  && apt-get update \
  && apt-get -y install python3 sudo dumb-init \
  && apt-get clean

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["sleep", "1d"]