collections:
  -
    name: containers.podman
    version: ">=1.18.0"
  -
    name: ansible.posix
    version: ">=2.1.0"
  -
    name: community.general
    version: ">=12.0.0"
  -
    name: community.sops
    version: ">=2.2.0"
